### ISSUE TITLE
Does the function "evaluate_detection()" give wrong return order of precision and recall?

### ISSUE THREAD

**Issue by JaywongWang** [ranjaykrishna/densevid_eval#2]
Hi Ranjay,
I found the function evaluate_detection() gives possibly wrong output order of precision and recall.
![default](https://user-images.githubusercontent.com/32317244/31448491-23884efa-aed7-11e7-8ca6-1b0274b675fa.PNG)
This means that precision and recall might be misused in other functions. 
Should it be changed to " return sum(precision) / len(precision), sum(recall) / len(recall) " ?
Did your paper report the right result (recall instead of precision) ?

**Comment by LuoweiZhou** [comment]
Can someone answer this question and look into the PR?

**Comment by ranjaykrishna** [comment]
This has been fixed by pullrequest #3

**Comment by LuoweiZhou** [comment]
Thanks, Ranjay. I assume the missing `unique_index += 1` in PR #3 will have some impacts on the evaluation score? Basically, all the misaligned segments are not counted
