### ISSUE TITLE
evaluation bug

### ISSUE THREAD

**Issue by rabbiteatcarrot** [ranjaykrishna/densevid_eval#6]
Hi ranjay,

I noticed a potential bug in your evaluation code as follows:
https://github.com/ranjaykrishna/densevid_eval/blob/master/evaluate.py#L196

It only utilizes the temporal proposals in the first groundtruth file to decide whether to add the garbage sentence rather than all groundtruth files.
So if the order of the groundtruth files changes, the evaluation results are different.
I think this part of code might be put outside of the for loop of groundtruth files.

**Comment by xh-liu** [comment]
Hi,
I also found this problem. I think the author actually intends to add a proposal to garbage only if it cannot match any ground-truth in all ground-truth files. So this part should be put outside the for loop.
Hope it can be fixed soon!

**Comment by kenjihata** [comment]
just saw this now. thanks for the catch! I should have added the fix.
